/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum NodeType {
  Unparsed = 0,
  Class = 1
}
export declare class Node {
  /** File path */
  name: string
  typ: NodeType
  /** Start line (0-based) */
  startLine: number
  /** End line (0-based) */
  endLine: number
  /** The code text */
  code: string
}
export declare class CodeGraph {
  constructor(dbPath: string)
  index(repoPath: string, sourcePath: string): void
  clean(delete: boolean): void
  query(stmt: string): Array<Node>
}
